apiVersion: v1
kind: Service
metadata:
  name: monitoring-demo
  namespace: default
  labels:
    app: monitoring-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: monitoring-demo