apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-demo
  namespace: monitoring
  labels:
    app: monitoring-demo
spec:
  selector:
    matchLabels:
      app: monitoring-demo
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s